# Bloom's minimal FFmpeg package wrapper. Generated by the superbuild after FFmpeg installs its
# shared libraries; it intentionally exposes no executable or upstream implementation details.
get_filename_component(_bloom_ffmpeg_prefix "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
set(FFmpeg_VERSION "8.1.2")
set(_bloom_ffmpeg_include_dir "${_bloom_ffmpeg_prefix}/include")
set(_bloom_ffmpeg_library_dir "${_bloom_ffmpeg_prefix}/lib")

foreach(_bloom_ffmpeg_library IN ITEMS avutil swresample swscale avcodec avformat avfilter avdevice)
    if(NOT EXISTS "${_bloom_ffmpeg_library_dir}/lib${_bloom_ffmpeg_library}.so")
        set(FFmpeg_FOUND FALSE)
        set(FFmpeg_NOT_FOUND_MESSAGE
            "Bloom FFmpeg prefix is missing lib${_bloom_ffmpeg_library}.so")
        return()
    endif()
    add_library("FFmpeg::${_bloom_ffmpeg_library}" SHARED IMPORTED)
    set_target_properties("FFmpeg::${_bloom_ffmpeg_library}" PROPERTIES
        IMPORTED_LOCATION "${_bloom_ffmpeg_library_dir}/lib${_bloom_ffmpeg_library}.so"
        INTERFACE_INCLUDE_DIRECTORIES "${_bloom_ffmpeg_include_dir}")
endforeach()

target_link_libraries(FFmpeg::swresample INTERFACE FFmpeg::avutil)
target_link_libraries(FFmpeg::swscale INTERFACE FFmpeg::avutil)
target_link_libraries(FFmpeg::avcodec INTERFACE FFmpeg::avutil FFmpeg::swresample)
target_link_libraries(FFmpeg::avformat INTERFACE FFmpeg::avcodec FFmpeg::avutil)
target_link_libraries(FFmpeg::avfilter INTERFACE FFmpeg::avutil FFmpeg::swresample)
target_link_libraries(FFmpeg::avdevice INTERFACE FFmpeg::avformat FFmpeg::avcodec FFmpeg::avutil)
set(FFmpeg_FOUND TRUE)
