from typing import Any
version: str
facade_version: str
class TaskTicket:
    @property
    def id(self) -> int: ...
    @property
    def cancelled(self) -> bool: ...
    def cancel(self) -> None: ...
    def progress(self, completed: int, total: int | None, phase: str) -> None: ...
    def finish(self, failure: str) -> None: ...
class Host:
    def __init__(self, project: str = ...) -> None: ...
    @property
    def headless(self) -> bool: ...
    @property
    def cancellation_requested(self) -> bool: ...
    @property
    def cancellation_epoch(self) -> int: ...
    def snapshot(self) -> dict[str, Any]: ...
    def schemas(self) -> list[dict[str, Any]]: ...
    def transact(self, operations: list[dict[str, Any]], label: str, revision: int) -> dict[str, Any]: ...
    def history(self, redo: bool) -> dict[str, Any]: ...
    def save(self, path: str) -> None: ...
    def render(self, composition: int, first: int, last: int, range: bool,
               preset: str, destination: str, cancellation_task: int) -> dict[str, Any]: ...
    def events(self) -> list[dict[str, Any]]: ...
    def tasks(self) -> list[dict[str, Any]]: ...
    def track_task(self, name: str) -> TaskTicket: ...
    def cancel(self, id: int) -> bool: ...
    def context(self) -> dict[str, Any]: ...
