from collections.abc import Mapping, Sequence
from typing import Any
class Proxy:
    id: int
    kind: str
    composition_id: int | None
    def resolve(self) -> Mapping[str, Any]: ...
    def __getattr__(self, name: str) -> Any: ...
    def __int__(self) -> int: ...
    def __repr__(self) -> str: ...
class Collection(Sequence[Proxy]):
    def get(self, identity: int) -> Proxy: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Proxy: ...
compositions: Collection
assets: Collection
def snapshot() -> Mapping[str, Any]: ...
def layers(composition: int | Proxy) -> Collection: ...
def nodes(composition: int | Proxy) -> Collection: ...
def parameters(composition: int | Proxy) -> Collection: ...
def curves(composition: int | Proxy) -> Collection: ...
