from collections.abc import Callable, Iterable, Mapping
from typing import Any
class Subscription:
    active: bool
    def close(self) -> None: ...
    def __enter__(self) -> Subscription: ...
    def __exit__(self, *args: Any) -> None: ...
def subscribe(callback: Callable[[Mapping[str, Any]], None], *,
              kinds: Iterable[str] = ...) -> Subscription: ...
def pump(*, limit: int = ...) -> int: ...
