# Generated from the host operation registry by the bloom.scripting.python-api test.
from collections.abc import Mapping
from fractions import Fraction
from typing import Any

from .data import Proxy

Time = int | tuple[int, int] | Fraction | float
Value = float | tuple[float, ...]

class Operation:
    id: str
    example: str
    schema: Mapping[str, Any]
    def __call__(self, *args: Any, **kwargs: Any) -> Mapping[str, Any] | None: ...

class AnimationOps:
    def convert_to_constant(self, parameter: int | Proxy, value: Value, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def create_for_parameter(self, parameter: int | Proxy, component: int = ..., *, composition: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...
    def delete_keyframe(self, curve: int | Proxy, keyframe: int | Proxy, component: int = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def delete_keyframes(self, keys: tuple, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def insert_color4_keyframe(self, curve: int | Proxy, value: tuple[float, float, float, float], interpolation: str = ..., *, composition: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...
    def insert_scalar_keyframe(self, curve: int | Proxy, value: float, interpolation: str = ..., *, composition: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...
    def insert_vec2_keyframe(self, curve: int | Proxy, value: tuple[float, float], interpolation: str = ..., *, composition: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...
    def insert_vec3_keyframe(self, curve: int | Proxy, value: tuple[float, float, float], interpolation: str = ..., *, composition: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...
    def move_keyframes(self, keys: tuple, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def paste_keyframes(self, keys: tuple, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_keyframe_at_time(self, curve: int | Proxy, value: Value, *, composition: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...
    def set_keyframe_at_time_for_parameter(self, parameter: int | Proxy, value: Value, *, composition: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...
    def set_keyframe_at_time_for_parameter_component(self, parameter: int | Proxy, component: int, value: float, *, composition: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...
    def set_keyframe_handles(self, outgoing: tuple = ..., incoming: tuple = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_keyframe_interpolation(self, curve: int | Proxy, keyframe: int | Proxy, interpolation: str, component: int = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_keyframe_values(self, values: tuple, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_keyframes_interpolation(self, keys: tuple, interpolation: str, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def update_color4_keyframe(self, curve: int | Proxy, keyframe: int | Proxy, value: tuple[float, float, float, float], interpolation: str = ..., *, composition: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...
    def update_scalar_keyframe(self, curve: int | Proxy, keyframe: int | Proxy, value: float, interpolation: str = ..., *, composition: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...
    def update_vec2_keyframe(self, curve: int | Proxy, keyframe: int | Proxy, value: tuple[float, float], interpolation: str = ..., *, composition: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...
    def update_vec3_keyframe(self, curve: int | Proxy, keyframe: int | Proxy, value: tuple[float, float, float], interpolation: str = ..., *, composition: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...

animation: AnimationOps

class AssetOps:
    def create_folder(self, name: str, parent: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def ensure_font(self, path: str, digest: str, family: str = ..., style: str = ..., index: int = ..., portability: str = ..., relinkHint: str = ..., name: str = ..., tags: tuple = ...) -> Mapping[str, Any] | None: ...
    def import_(self, paths: tuple, projectDirectory: str) -> Mapping[str, Any] | None: ...
    def move(self, assets: tuple, folder: int | Proxy = ..., index: int = ...) -> Mapping[str, Any] | None: ...
    def relink(self, asset: int | Proxy, path: str, projectDirectory: str) -> Mapping[str, Any] | None: ...
    def relink_font(self, asset: int | Proxy, path: str, digest: str, family: str = ..., style: str = ..., index: int = ..., portability: str = ..., relinkHint: str = ..., name: str = ..., tags: tuple = ...) -> Mapping[str, Any] | None: ...
    def remove(self, asset: int | Proxy) -> Mapping[str, Any] | None: ...
    def remove_folder(self, folder: int | Proxy) -> Mapping[str, Any] | None: ...
    def rename(self, asset: int | Proxy, name: str) -> Mapping[str, Any] | None: ...
    def rename_folder(self, folder: int | Proxy, name: str) -> Mapping[str, Any] | None: ...
    def reorder(self, order: tuple, folder: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_tags(self, assets: tuple, tags: tuple) -> Mapping[str, Any] | None: ...

asset: AssetOps

class CompositionOps:
    def add(self, name: str, width: int = ..., height: int = ..., duration: Time = ..., frameRateNumerator: int = ..., frameRateDenominator: int = ..., background: tuple[float, float, float, float] = ...) -> Mapping[str, Any] | None: ...
    def clear_work_area(self, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def delete(self, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def duplicate(self, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_background_color(self, color: tuple[float, float, float, float], *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_duration(self, duration: Time, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_format(self, width: int, height: int, frameRateNumerator: int = ..., frameRateDenominator: int = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_name(self, name: str, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_safe_areas(self, action: float = ..., title: float = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_work_area(self, start: Time, end: Time, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...

composition: CompositionOps

class DataBlockOps:
    def create(self, typeId: str, mediaType: str, kind: str = ..., payloadKind: str = ..., payload: tuple = ..., text: str = ..., createdAt: str = ..., schemaMajor: int = ..., schemaMinor: int = ..., tags: tuple = ...) -> Mapping[str, Any] | None: ...
    def relink(self, dataBlock: int | Proxy, path: str, locatorKind: str = ..., portability: str = ..., relinkHint: str = ...) -> Mapping[str, Any] | None: ...
    def remove(self, dataBlock: int | Proxy) -> Mapping[str, Any] | None: ...
    def replace_payload(self, dataBlock: int | Proxy, payloadKind: str = ..., payload: tuple = ..., text: str = ...) -> Mapping[str, Any] | None: ...
    def set_tags(self, dataBlock: int | Proxy, tags: tuple) -> Mapping[str, Any] | None: ...

data_block: DataBlockOps

class LayerOps:
    def add_audio(self, asset: int | Proxy, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def add_image(self, asset: int | Proxy, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def add_shape(self, kind: str, position: tuple[float, float] = ..., size: tuple[float, float] = ..., lineStart: tuple[float, float] = ..., lineEnd: tuple[float, float] = ..., path: tuple = ..., pathClosed: bool = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def add_solid(self, name: str, color: tuple[float, float, float, float], position: tuple[float, float] = ..., opacity: float = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def add_text(self, name: str, text: str, position: tuple[float, float] = ..., opacity: float = ..., size: float = ..., color: tuple[float, float, float, float] = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def move_before(self, slot: int | Proxy, before: int | Proxy = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def rename(self, name: str, *, composition: int | Proxy = ..., layer: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_enabled(self, enabled: bool, *, composition: int | Proxy = ..., layer: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_label_color(self, color: tuple[float, float, float] = ..., *, composition: int | Proxy = ..., layer: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_locked(self, locked: bool, *, composition: int | Proxy = ..., layer: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_parent(self, parent: int | Proxy = ..., *, composition: int | Proxy = ..., layer: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_range(self, start: Time, end: Time, *, composition: int | Proxy = ..., layer: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_solo(self, solo: bool, *, composition: int | Proxy = ..., layer: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def split_at_time(self, *, composition: int | Proxy = ..., layer: int | Proxy = ..., time: Time = ...) -> Mapping[str, Any] | None: ...

layer: LayerOps

class MergeOps:
    def reorder_input(self, merge: int | Proxy, slot: int | Proxy, index: int, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_enabled(self, merge: int | Proxy, enabled: bool, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...

merge: MergeOps

class NodeOps:
    def add(self, nodeType: str, position: tuple[float, float] = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def connect(self, sourceNode: int | Proxy, sourcePort: str, targetNode: int | Proxy, port: str = ..., role: str = ..., slot: int | Proxy = ..., insertBefore: int | Proxy = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def disconnect_input(self, node: int | Proxy, port: str = ..., role: str = ..., slot: int | Proxy = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def dissolve(self, node: int | Proxy, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def duplicate(self, offset: tuple[float, float] = ..., *, composition: int | Proxy = ..., nodes: tuple = ...) -> Mapping[str, Any] | None: ...
    def move(self, positions: tuple, groups: tuple = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def remove(self, *, composition: int | Proxy = ..., nodes: tuple = ...) -> Mapping[str, Any] | None: ...
    def set_collapsed(self, node: int | Proxy, collapsed: bool, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_muted(self, node: int | Proxy, muted: bool, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_width(self, node: int | Proxy, width: float, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...

node: NodeOps

class NodeGroupOps:
    def create(self, name: str = ..., *, composition: int | Proxy = ..., nodes: tuple = ...) -> Mapping[str, Any] | None: ...
    def remove(self, group: int | Proxy, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def rename(self, group: int | Proxy, name: str, *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...
    def set_members(self, group: int | Proxy, *, composition: int | Proxy = ..., members: tuple = ...) -> Mapping[str, Any] | None: ...

node_group: NodeGroupOps

class ParameterOps:
    def set_source(self, parameter: int | Proxy, value: Value = ..., curve: int | Proxy = ..., driverNode: int | Proxy = ..., driverPort: str = ..., *, composition: int | Proxy = ...) -> Mapping[str, Any] | None: ...

parameter: ParameterOps

class ProjectOps:
    def set_name(self, name: str) -> Mapping[str, Any] | None: ...

project: ProjectOps

def registry() -> Mapping[str, Operation]: ...
def get(operation_id: str) -> Operation: ...
