from collections.abc import Mapping
from typing import Any
from .data import Proxy

class Operation:
    id: str
    schema: Mapping[str, Any]
    def __call__(self, **kwargs: Any) -> Mapping[str, Any] | None: ...

class AnimationOps:
    def convert_to_constant(self) -> Mapping[str, Any] | None: ...
    def create_for_parameter(self, *, composition: int | Proxy, parameter: int | Proxy, time: tuple[int, int]) -> Mapping[str, Any] | None: ...
    def delete_keyframe(self) -> Mapping[str, Any] | None: ...
    def delete_keyframes(self) -> Mapping[str, Any] | None: ...
    def insert_color4_keyframe(self) -> Mapping[str, Any] | None: ...
    def insert_scalar_keyframe(self) -> Mapping[str, Any] | None: ...
    def insert_vec2_keyframe(self) -> Mapping[str, Any] | None: ...
    def insert_vec3_keyframe(self) -> Mapping[str, Any] | None: ...
    def move_keyframes(self) -> Mapping[str, Any] | None: ...
    def paste_keyframes(self) -> Mapping[str, Any] | None: ...
    def set_keyframe_at_time(self) -> Mapping[str, Any] | None: ...
    def set_keyframe_at_time_for_parameter(self) -> Mapping[str, Any] | None: ...
    def set_keyframe_at_time_for_parameter_component(self, *, composition: int | Proxy, parameter: int | Proxy, component: int, time: tuple[int, int], value: float) -> Mapping[str, Any] | None: ...
    def set_keyframe_handles(self) -> Mapping[str, Any] | None: ...
    def set_keyframe_interpolation(self) -> Mapping[str, Any] | None: ...
    def set_keyframe_values(self) -> Mapping[str, Any] | None: ...
    def set_keyframes_interpolation(self) -> Mapping[str, Any] | None: ...
    def update_color4_keyframe(self) -> Mapping[str, Any] | None: ...
    def update_scalar_keyframe(self) -> Mapping[str, Any] | None: ...
    def update_vec2_keyframe(self) -> Mapping[str, Any] | None: ...
    def update_vec3_keyframe(self) -> Mapping[str, Any] | None: ...

animation: AnimationOps

class AssetOps:
    def create_folder(self) -> Mapping[str, Any] | None: ...
    def ensure_font(self) -> Mapping[str, Any] | None: ...
    def import_(self) -> Mapping[str, Any] | None: ...
    def move(self) -> Mapping[str, Any] | None: ...
    def relink(self) -> Mapping[str, Any] | None: ...
    def relink_font(self) -> Mapping[str, Any] | None: ...
    def remove(self) -> Mapping[str, Any] | None: ...
    def remove_folder(self) -> Mapping[str, Any] | None: ...
    def rename(self) -> Mapping[str, Any] | None: ...
    def rename_folder(self) -> Mapping[str, Any] | None: ...
    def reorder(self) -> Mapping[str, Any] | None: ...
    def set_tags(self) -> Mapping[str, Any] | None: ...

asset: AssetOps

class CompositionOps:
    def add(self, *, name: str, width: int, height: int, duration: tuple, frameRateNumerator: int = ..., frameRateDenominator: int = ...) -> Mapping[str, Any] | None: ...
    def clear_work_area(self) -> Mapping[str, Any] | None: ...
    def delete(self, *, composition: int | Proxy) -> Mapping[str, Any] | None: ...
    def duplicate(self, *, composition: int | Proxy) -> Mapping[str, Any] | None: ...
    def set_background_color(self) -> Mapping[str, Any] | None: ...
    def set_duration(self) -> Mapping[str, Any] | None: ...
    def set_format(self) -> Mapping[str, Any] | None: ...
    def set_name(self, *, composition: int | Proxy, name: str) -> Mapping[str, Any] | None: ...
    def set_safe_areas(self) -> Mapping[str, Any] | None: ...
    def set_work_area(self) -> Mapping[str, Any] | None: ...

composition: CompositionOps

class LayerOps:
    def add_audio(self) -> Mapping[str, Any] | None: ...
    def add_image(self) -> Mapping[str, Any] | None: ...
    def add_shape(self) -> Mapping[str, Any] | None: ...
    def add_solid(self, *, composition: int | Proxy, name: str, color: tuple[float, float, float, float], position: tuple[float, float] = ..., opacity: float = ...) -> Mapping[str, Any] | None: ...
    def add_text(self, *, composition: int | Proxy, name: str, text: str, position: tuple[float, float] = ..., opacity: float = ..., size: float = ..., color: tuple[float, float, float, float] = ...) -> Mapping[str, Any] | None: ...
    def move_before(self) -> Mapping[str, Any] | None: ...
    def rename(self) -> Mapping[str, Any] | None: ...
    def set_enabled(self) -> Mapping[str, Any] | None: ...
    def set_label_color(self) -> Mapping[str, Any] | None: ...
    def set_locked(self) -> Mapping[str, Any] | None: ...
    def set_parent(self) -> Mapping[str, Any] | None: ...
    def set_range(self) -> Mapping[str, Any] | None: ...
    def set_solo(self) -> Mapping[str, Any] | None: ...
    def split_at_time(self) -> Mapping[str, Any] | None: ...

layer: LayerOps

class MergeOps:
    def reorder_input(self) -> Mapping[str, Any] | None: ...
    def set_enabled(self) -> Mapping[str, Any] | None: ...

merge: MergeOps

class NodeGroupOps:
    def create(self) -> Mapping[str, Any] | None: ...
    def remove(self) -> Mapping[str, Any] | None: ...
    def rename(self) -> Mapping[str, Any] | None: ...
    def set_members(self) -> Mapping[str, Any] | None: ...

node_group: NodeGroupOps

class NodeOps:
    def add(self, *, composition: int | Proxy, nodeType: str, position: tuple[float, float]) -> Mapping[str, Any] | None: ...
    def connect(self) -> Mapping[str, Any] | None: ...
    def disconnect_input(self) -> Mapping[str, Any] | None: ...
    def dissolve(self) -> Mapping[str, Any] | None: ...
    def duplicate(self) -> Mapping[str, Any] | None: ...
    def move(self) -> Mapping[str, Any] | None: ...
    def remove(self, *, composition: int | Proxy, nodes: tuple[int, ...]) -> Mapping[str, Any] | None: ...
    def set_collapsed(self) -> Mapping[str, Any] | None: ...
    def set_muted(self) -> Mapping[str, Any] | None: ...
    def set_width(self) -> Mapping[str, Any] | None: ...

node: NodeOps

class ParameterOps:
    def set_source(self) -> Mapping[str, Any] | None: ...

parameter: ParameterOps

class ProjectOps:
    def set_name(self, *, name: str) -> Mapping[str, Any] | None: ...

project: ProjectOps

def registry() -> Mapping[str, Operation]: ...
def get(operation_id: str) -> Operation: ...
