from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, Generic, TypeVar
_T = TypeVar('_T')
@dataclass(frozen=True)
class Progress:
    completed: int = ...
    total: int | None = ...
    phase: str = ...
class TaskHandle(Generic[_T]):
    @property
    def progress(self) -> Progress: ...
    @property
    def cancellation_requested(self) -> bool: ...
    @property
    def done(self) -> bool: ...
    def cancel(self) -> bool: ...
    def check_cancelled(self) -> None: ...
    def report_progress(self, completed: int = ..., total: int | None = ..., phase: str = ...) -> None: ...
    def result(self, timeout: float | None = ...) -> _T: ...
def submit(function: Callable[..., _T], *args: Any, **kwargs: Any) -> TaskHandle[_T]: ...
def snapshots() -> tuple: ...
def cancel(task_id: int) -> bool: ...
