from collections.abc import Mapping
from typing import Any
class group:
    result: Mapping[str, Any] | None
    def __init__(self, label: str, *, expected_revision: int | None = ...) -> None: ...
    def __enter__(self) -> group: ...
    def __exit__(self, kind: Any, value: Any, traceback: Any) -> bool: ...
def undo() -> Mapping[str, Any]: ...
def redo() -> Mapping[str, Any]: ...
