if(NOT DEFINED BLOOM_DEPENDENCY_PREFIX)
    message(FATAL_ERROR "BLOOM_DEPENDENCY_PREFIX is required")
endif()

file(GLOB openh264_runtime_files
     "${BLOOM_DEPENDENCY_PREFIX}/lib/libopenh264.so.*")
if(openh264_runtime_files)
    message(FATAL_ERROR "OpenH264 runtime binary leaked into the dependency prefix")
endif()

file(GLOB avcodec_files "${BLOOM_DEPENDENCY_PREFIX}/lib/libavcodec.so.*")
if(NOT avcodec_files)
    message(FATAL_ERROR "FFmpeg avcodec shared object is absent")
endif()
list(SORT avcodec_files)
list(GET avcodec_files 0 avcodec)
execute_process(COMMAND readelf -d "${avcodec}" OUTPUT_VARIABLE dynamic OUTPUT_STRIP_TRAILING_WHITESPACE
                RESULT_VARIABLE readelf_status)
if(NOT readelf_status EQUAL 0)
    message(FATAL_ERROR "readelf could not inspect FFmpeg avcodec")
endif()
if(NOT dynamic MATCHES "NEEDED.*libopenh264\\.so\\.8")
    message(FATAL_ERROR "FFmpeg avcodec does not name libopenh264.so.8")
endif()
if(dynamic MATCHES "(RPATH|RUNPATH)")
    message(FATAL_ERROR "FFmpeg avcodec has a runtime path to the private OpenH264 stub")
endif()

message(STATUS "OpenH264 prefix boundary passed: private link stub only; DT_NEEDED libopenh264.so.8")

if(DEFINED BLOOM_MEDIA_WORKER_RUNTIME)
    if(NOT IS_DIRECTORY "${BLOOM_MEDIA_WORKER_RUNTIME}")
        message(FATAL_ERROR "OpenH264 worker runtime directory is absent")
    endif()
    file(GLOB shim_files "${BLOOM_MEDIA_WORKER_RUNTIME}/libopenh264.so*")
    if(NOT shim_files)
        message(FATAL_ERROR "OpenH264 worker runtime has no shim")
    endif()
    list(SORT shim_files)
    foreach(shim IN LISTS shim_files)
        execute_process(COMMAND readelf -d "${shim}" OUTPUT_VARIABLE shim_dynamic
                        OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE shim_readelf_status)
        if(NOT shim_readelf_status EQUAL 0 OR NOT shim_dynamic MATCHES
                                                   "SONAME.*libopenh264\.so\.8")
            message(FATAL_ERROR "Worker runtime contains a non-shim OpenH264 library: ${shim}")
        endif()
    endforeach()
    list(GET shim_files 0 shim)
    execute_process(COMMAND nm -D --defined-only --format=posix "${shim}" OUTPUT_VARIABLE exports
                    OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE nm_status)
    if(NOT nm_status EQUAL 0)
        message(FATAL_ERROR "nm could not inspect the OpenH264 shim")
    endif()
    set(expected_exports
        WelsCreateSVCEncoder WelsDestroySVCEncoder WelsCreateDecoder WelsDestroyDecoder
        WelsGetCodecVersion WelsGetCodecVersionEx)
    foreach(symbol IN LISTS expected_exports)
        if(NOT exports MATCHES "${symbol}(@@[^ ]+)? ")
            message(FATAL_ERROR "OpenH264 shim is missing required export ${symbol}")
        endif()
    endforeach()
    string(REGEX MATCHALL "Wels[A-Za-z0-9_]+(@@[^ ]+)? " actual_export_lines "${exports}")
    set(actual_exports)
    foreach(line IN LISTS actual_export_lines)
        string(STRIP "${line}" line)
        string(REGEX REPLACE " .*$" "" symbol "${line}")
        string(REGEX REPLACE "@@.*$" "" symbol "${symbol}")
        list(APPEND actual_exports "${symbol}")
    endforeach()
    list(SORT actual_exports)
    list(SORT expected_exports)
    if(NOT actual_exports STREQUAL expected_exports)
        message(FATAL_ERROR "OpenH264 shim exports codec symbols beyond its six-symbol ABI")
    endif()
    message(STATUS "OpenH264 worker boundary passed: shim-only runtime with six ABI exports")
endif()
